void main() {
  print((-10).abs());
  print((10.5).abs());
  print(10.9.ceil());
  print((-10.9).ceil());
  print((-0.9).ceil());
  print(0.7.ceil());
  print((-1.7).ceil());
  print(1.7.floor());
  print(0.7.floor());
  print((-1.7).floor());
  print((-0.7).floor());
  //print(5.compareTo(10));
  //print(10.compareTo(5));
  print(-10.compareTo(11));
  print(10.compareTo(-10));
  print(10.compareTo(10));
  print(10.remainder(3));
  print(10.5.remainder(3));
  print(10.remainder(-3));
  print(-10.remainder(-3));
  print(10.remainder(3));
  print(10.3.round());
  print(-10.5.round());
  print(4.toDouble());
  print(4.5.toString());
  print(double.parse("4"));
  print(int.parse("4"));
  print(int.tryParse("4.5"));
  String tt = "4.5";
  double d = double.parse(tt);
  int s = d.toInt();
  print(s);
  print(10.toDouble());
  int c = double.parse("10.5").toInt();
  print(c);
}
